{% set version = "0.5" %}

package:
  name: win_unicode_console
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/win_unicode_console/win_unicode_console-{{ version }}.zip
  sha256: d4142d4d56d46f449d6f00536a73625a871cba040f0bc1a2e305a04578f07d1e

build:
  number: 1005
  skip: True  # [not win]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python

test:
  imports:
    - win_unicode_console

about:
  home: https://github.com/Drekin/win-unicode-console
  license: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'A Python package to enable Unicode input and display when running Python from Windows console'

extra:
  recipe-maintainers:
    - minrk
    - ocefpaf
