travis:
  secure:
    BINSTAR_TOKEN: OAAZdyKIR3M/CWMc/Wz/VdtSvSMd6bz9++IPYNR8sncQp3aOTdicI5CzRtS4SOmBEbcQBYyVB8tIjR+cr4SiTraQiiEnApDh9db7UcBtuWDWa6XGnYILEtmjHR1BSiNLIVV5D8sg+DbOLMltmv0eJ1Dndd3ftIzVRKgigpixYdaLnALF+rU2IokEIrqsbXlqnPLd1kIbHnw7Svv+sa54LwUTV+MerA0LRWslDf+Y2Iy9V+IlLUqix0uAtYfKVWW0xlIQ5mZaYTQ06L21CMrjqeAcoFCjzQXjPysJKWwHCpig/HHqKz8MHLp0STUnJrBAvYzyeeyVBAoSvWTemK+Dn7pOZjxg1fWk0lga62GnJ8DcYP9F8h8993G9eCL7SUYRsroLqVXQO+7IhfAgo9uOim6/OXlJ9pBYfcw+b/rl2X51oRMruvbTWCtjSX2P/jpoCKPez2t4LsgYo0KywkwprGSDlOgKH+UrWI0Ay+jnv7j89oYDrXY9OgIeoWM1V0SMabA60dlbYwLx8ieP1LHTsBUiGzES3lRiJ0aFADIaCV9FVwlx7UKdPzbl8qEsFFdecKmyP3YqkpZ+01x1IrAEQy6PGzj3QwqiCnBqGquVdH10zLe+kNnaj54zNDeZlvPI4aySN4cayR3l9quytQ0i6sR4dUOlX+lpOR/TF3yhkb0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
