appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ebUIT/iLu3gB1QlGy754+8ymGudfhTK/6q950e/28QrUdgYI9XErY8jau5lKtYL6Pkf5xbODOz1U0BHcKeZaeeNLgljiBoQyuRgFmcl68raIaz1Aoh5EhEUaxcZIAxIi28bxF0KuRXDK4nYVVj+5vQlDsWLp+Ihs7gvdFW9X7AVnK9mHrwRS246JHEU66W/bAHjfncd1AVqNLXrir5f+0Qk5O+IpKEl5dKrZ3JBDFPLYOjDADozb3fNR42jwueLQ0wC9ErSgV7KB45Lc7Va7Njhn69IDsTAzjQBtFiJGdsPNyMbRK0KwLW7qvU8ddiGpXQnz844B6AtrlNLSrspxltXfzld5+W+ka0cx21M+m8yAUPhnJ6rhcl5FdjtMJcmQcCtfzVnzyAmgiRLrWG/VlpbCGmeXl8YLD2xCNPXw5gApPEZmIsiUEwSeveJYrOwYGhulx58eKbbclR+CWsC2im/BsdoH+P3SWlCynsxxnup0pkMg9JMMFuUUieTdYi6pYhtZEZUh52SRzElDR5PgYNkYAILgiFsL0VUHUUbpHZDifpSHggbvHc0bxlDvY3L55xTiT9VullrZPIGfUjrIDpCLTpySo3dKBMKd8HooIseSEo2mNpw/PKAKf9sR8JA7lir1JeqRw6jwI1s3vOlgD9JdFYBQyDMifCOdQtBSlvc=}
